@startuml

title Karbor Protectables

hide circle

legend top
This file contains the dependency between protectables in the default
distribution of Karbor. The arrows, similar to inheritance point to the parent
since Protectables define what types they depend on so this reflects who is
responsible for the connection.
endlegend

class OS::Glance::Image extends OS::Nova::Server, OS::Keystone::Project

class OS::Cinder::Volume extends OS::Nova::Server, OS::Keystone::Project

class OS::Nova::Server extends OS::Keystone::Project

class OS::Keystone::Project

class OS::Neutron::Topology extends OS::Keystone::Project

class OS::Manila::Share extends OS::Keystone::Project

@enduml
