- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - check-requirements
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - karbor-dsvm-fullstack:
            voting: false

- job:
    name: karbor-dsvm-fullstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/karbor-dsvm-fullstack/run.yaml
    post-run: playbooks/legacy/karbor-dsvm-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/karbor
      - openstack/python-karborclient
      - openstack/trove
      - openstack/trove-dashboard
      - openstack/manila-tempest-plugin
